
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.7
    container_name: postDb
    restart: always
    ports:
      - 6432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: usersDb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080